# permissions for end users to edit buckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: s3-operator
    app.kubernetes.io/managed-by: kustomize
  name: bucket-editor-role
rules:
- apiGroups:
  - s3.onestein.nl
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.onestein.nl
  resources:
  - buckets/status
  verbs:
  - get
